### ISSUE TITLE
Passing model object to link-to component breaks task-oriented templates

### ISSUE THREAD

**Issue by allthesignals** [knownasilya/ember-data-tasks#4]
If you are passing full model objects to your `link-to` components, it is default Ember behavior to have that object override the model hook entirely. This can lead to some mysterious `undefined` errors. It makes switching to data tasks less than smooth.

```handlebars
{{#link-to 'lot' lot.bookmark}}
  Link
{{/link-to}}
```

The trick is to pass ids. In our case, `lot.bookmark`'s route dynamic segment is more complicated, require some additional logic for parsing out the full id. 

I'm not sure there is an out-of-the-box solution for this, but it is awkward to require avoiding passing full model objects - I'm not sure what the solution would be other than defensively wrapping resolved "real" model objects in an object as part of the API, as the template expects.

**Comment by knownasilya** [comment]
For your case I'd use a helper to parse out the id. Will think about this a bit more.

**Comment by allthesignals** [comment]
@knownasilya agreed - I landed on this:

```handlebars
{{#with (bbl-demux lot.bookmark.id) as |bblObj|}}
  {{#link-to 'lot' bblObj.boro bblObj.block bblObj.lot}}
    {{lot.bookmark.address}}
    <span class="dark-gray">
      {{lot.bookmark.bbl}}
    </span>
  {{/link-to}}
{{/with}}
```

This issue is easy to work around so is low priority, but it's something to think about in terms of availability of Ember's  expected functionality.

**Comment by knownasilya** [comment]
I'd have done something like

```hbs
{{#link-to 'lot' (bbl-demux lot.bookmark.id)}}
...
{{/link-to}}
```

And use a separator like '.' or something. But I'm not as close to the code as you are, so your approach might be better.

**Comment by allthesignals** [comment]
Yeah, I wanted to do that, but my "demux" helper returns an object, and I'm not sure how to get "spread" operator logic to work in templates. Otherwise, to the route, it's just another object. But maybe I'm missing something. 

(I'm aware of some conversation about spread-operator-like syntax in handlebars, but I'm not sure if there was any progress on that).

**Comment by knownasilya** [comment]
Just not sure if your above example is more ceremony then

```js
model({ bbl }) {
  let idObject = demux(bbl);
  // let id = bbl.split('.');
}
```

**Comment by allthesignals** [comment]
Aaah - I found an alternative. I have the "demux" logic available as computeds on the model:
```
{{#link-to 'lot' lot.bookmark.boro lot.bookmark.block lot.bookmark.lot}}
  link 
{{/link-to}}
```
"Ceremonial" is a good word for that!

Our [demux](https://github.com/NYCPlanning/labs-zola/blob/develop/app/utils/bbl-demux.js) utility does different things based on the arguments, which made sense for the [route](https://github.com/NYCPlanning/labs-zola/blob/develop/app/models/lot.js) at the time... maybe it's time for a refactor. 

Anyway, I think the original issue here still stands for now. If our route's model hook is this:
```
  model(params) {
    const id = bblDemux(params);
    return {
      taskInstance: this.store.findRecord('lot', id),
    };
  },
```

Passing a full object to link-to will bypass that hook completely, avoiding the object wrapping.

**Comment by knownasilya** [comment]
You could also do something like:

```hbs
{{#link-to 'lot' (hash taskInstance=lot.bookmark)}}
```
On another note, there is also a consensus in the community that the behavior of the `model` hook is tricky, and there is an open RFC about it: https://github.com/emberjs/rfcs/pull/283.
This problem isn't specific to this addon, you'd also encounter it if using `RSVP.hash` or `RSVP.all`. An alternative with tasks is to always make them on the controller, and have the route just pass down any params.

**Comment by knownasilya** [comment]
Closing this, feel free to continue the discussion.
