### ISSUE TITLE
Upgrade ember-cli-babel

### ISSUE THREAD

**Issue by allthesignals** [knownasilya/ember-data-tasks#8]
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: labs-zola -> ember-data-tasks -> ember-cli-babel

**Comment by knownasilya** [comment]
Fixed in v1.1.0

**Comment by allthesignals** [comment]
Thanks :)

**Comment by knownasilya** [comment]
@allthesignals probably worth adding docs for the other commit that's in this release.
